"""add users and invites

Revision ID: 2bc56d7af600
Revises: 9f55488740f8
Create Date: 2025-12-16 19:19:54.827958

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2bc56d7af600"
down_revision: Union[str, Sequence[str], None] = "9f55488740f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("login_id", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "user", name="user_role", native_enum=False),
            server_default="user",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "active", "disabled", name="user_status", native_enum=False),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login_id"),
    )
    op.create_table(
        "invites",
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column(
            "role", sa.Enum("admin", "user", name="invite_role", native_enum=False), nullable=False
        ),
        sa.Column("issued_by", sa.Integer(), nullable=False),
        sa.Column("provisional_user_id", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issued_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provisional_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invites")
    op.drop_table("users")
    # ### end Alembic commands ###
