"""Initial migration

Revision ID: 9f55488740f8
Revises:
Create Date: 2025-12-11 17:11:30.521258

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9f55488740f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('is_enterprise', sa.Boolean(), nullable=True),
    sa.Column('dividend_yield', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('stock_prices',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('high', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('low', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('close', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_index('idx_stock_prices_symbol_date', 'stock_prices', ['symbol', 'date'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ma_25', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('divergence_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('dividend_yield', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('volume_avg_20', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_index('idx_technical_indicators_symbol_date', 'technical_indicators', ['symbol', 'date'], unique=False)
    op.create_table('ticker_info',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('full_time_employees', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('current_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('dividend_yield', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('dividend_rate', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('trailing_annual_dividend_rate', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('ex_dividend_date', sa.Date(), nullable=True),
    sa.Column('trailing_pe', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('forward_pe', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('price_to_book', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('return_on_equity', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('return_on_assets', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('total_revenue', sa.BigInteger(), nullable=True),
    sa.Column('earnings_growth', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('revenue_growth', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('profit_margins', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('fifty_two_week_high', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('fifty_two_week_low', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('average_volume', sa.BigInteger(), nullable=True),
    sa.Column('corporate_actions_dividend', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index('idx_ticker_info_last_updated', 'ticker_info', ['last_updated'], unique=False)
    op.create_index('idx_ticker_info_symbol', 'ticker_info', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ticker_info_symbol', table_name='ticker_info')
    op.drop_index('idx_ticker_info_last_updated', table_name='ticker_info')
    op.drop_table('ticker_info')
    op.drop_index('idx_technical_indicators_symbol_date', table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_index('idx_stock_prices_symbol_date', table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_table('companies')
    # ### end Alembic commands ###
